In [2]:
import requests
import pandas as pd

NIVEL 1

In [3]:
import requests

r = requests.get("https://jsonplaceholder.typicode.com/posts/1")
print(r.status_code)
print(r.json())

200
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

Ejercicio 1: Usando.get hacemos las primeras peticiones.Pedimos la lista de todas las publicaciones, users y todos.

In [4]:

r_posts = requests. get("https://jsonplaceholder.typicode.com/posts")
r_users = requests. get("https://jsonplaceholder.typicode.com/users")
r_todos = requests. get("https://jsonplaceholder.typicode.com/todos")

Ejercicio 2: Comprobamos el estado y la cantidad de las peticiones. 
El código que nos aparece de estado es de 200, significaa que la petición ha sido procesada correctamente.
Se mostratará las dos opciones con loop y sin loop.

In [5]:

#Con loop
recursos = {
    "posts": r_posts,
    "users": r_users,
    "todos": r_todos
}
for nombre, respuesta in recursos.items():
    print(f"{nombre} el estado es: {respuesta.status_code} | la cantidad es: {len(respuesta.json())}")
    
#Sin loop 
# El estado : 

print("El status de posts es:", r_posts.status_code),
print("El status de users es:", r_users.status_code),
print("El status de todos es:", r_todos.status_code)

#La cantidad es de: 
print("La cantidad de posts es:", len(r_posts.json())),
print("La cantidad de users es:", len(r_users.json())),
print("La cantidad de todos es:", len(r_todos.json()))

posts el estado es: 200 | la cantidad es: 100
users el estado es: 200 | la cantidad es: 10
todos el estado es: 200 | la cantidad es: 200
El status de posts es: 200
El status de users es: 200
El status de todos es: 200
La cantidad de posts es: 100
La cantidad de users es: 10
La cantidad de todos es: 200

Aquí veremos las peticiones originalmente en Json en Dataframes. 
Usamos json_normalize para evitar columnas anidadas como  "adress" de Users.

In [6]:

recursos = {
    "posts": r_posts,
    "users": r_users,
    "todos": r_todos
}

dataframes = {}
for nombre, respuesta in recursos.items():
    dataframes[nombre] = pd.json_normalize(respuesta.json())

In [7]:
dataframes["posts"].head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [8]:
dataframes["users"].head()

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

In [9]:
dataframes["todos"].head()

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

Ejercicio 3: Recibir un error 404, para ello buscamos el post IrinaAndrade que sabemoos que no consta.

In [10]:

r_error404 = requests. get("https://jsonplaceholder.typicode.com/IrinaAndrade")
print(r_error404)
print("Estado del post inexistente:", r_error404.status_code)

<Response [404]>
Estado del post inexistente: 404

Ejercicio 4. Nueva publicación: 
Creamos una variable con un diccionario con las partes del post:título, cuerpo del post y el usuario que ha escrito el post.
Guardamos la petición del post en una variable. Si aparece el código 201 es que se ha creado correctamente.

In [11]:

Nuevo_Post= {
    "title":"Un,dos,tres probando",
    "body":"Aqui aparece el contenido de prueba",
    "userId":97
}

 
r_Npost= requests.post("https://jsonplaceholder.typicode.com/posts", json= Nuevo_Post)

print("Estado del nuevo post es:", r_Npost.status_code)
print("La respuesta al post es:", r_Npost.json())

Estado del nuevo post es: 201
La respuesta al post es: {'title': 'Un,dos,tres probando', 'body': 'Aqui aparece el contenido de prueba', 'userId': 97, 'id': 101}

Ejercicio 5. Modificamos una publicación parcialmente usando el método .patch.
Cambiamos el título de una variable existente usando un diccionario+método patch.
Para comprobar si los cambios se  han realizado bien revisamos si el status esta a 200.

In [12]:

Modificaciones = {"title": "123 probando"}
r_patch = requests.patch("https://jsonplaceholder.typicode.com/posts/1", json=Modificaciones)
print("El estado de PATCH es:", r_patch.status_code)
print("La respuesta para PATCH es:", r_patch.json())

El estado de PATCH es: 200
La respuesta para PATCH es: {'userId': 1, 'id': 1, 'title': '123 probando', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

Ejercicio 6. Solicitar un Delete. Para borrar un post debemos usar el .delete especificando la URL.

In [13]:

r_delete = requests.delete("https://jsonplaceholder.typicode.com/posts/1")
print("El estado del Delete es:", r_delete.status_code)
print("La respuesta del Delete es:", r_delete.json())

El estado del Delete es: 200
La respuesta del Delete es: {}

NIVEL 3

Ejercicio 1: Usar la API de Open Data Bcn para: Encontrar un dataset de interés vía  package_search y package_show.

In [14]:
url_bcn = "https://opendata-ajuntament.barcelona.cat/data/api/action"

Ejercicio 1: Buscamos por mi tema de interés: Ocupación, empleo.

In [15]:
busqueda = requests.get(
    url_bcn + "/package_search", 
    params={"q": "ocupacions"})

print("Estado package_search:", busqueda.status_code)

resultados_search = busqueda.json()["result"]["results"]
for dataset in resultados_search [:5]:
    print(dataset["title"], "| name:", dataset["name"])

Estado package_search: 200
Factsheets on labor market occupations in the city of Barcelona | name: fitxes-ocupacionals

Usamos el package_show: para ver en  detalle el dataset de fitxe ocupacioals con el bucle for revisaremos e identificaremos los fichermos disponibles para poder elegir uno.

In [16]:
respuesta_show = requests.get(
    url_bcn + "/package_show",
    params={"id": "fitxes-ocupacionals"})
print("Estado package_show:", respuesta_show.status_code)

detalle = respuesta_show.json()["result"]

for recurso in detalle["resources"]:
    print(recurso["name"], recurso["id"], "| formato:", recurso["format"])

Estado package_show: 200
Fitxes_ocupacionals.csv eda0577b-9ed6-445b-abde-24cd65913716 | formato: CSV
Fichas_ocupacionales.csv d3fffd9f-863c-47a0-bbac-0480b52a5c8b | formato: CSV
Occupational_files.csv b635dec4-0d46-4c91-9154-11d99928af10 | formato: CSV

Ejercicio 2: De los recurso displonibles eegimos el fichero "Fitxes_ocupacionals.csv"
Fitxes_ocupacionals.csv eda0577b-9ed6-445b-abde-24cd65913716 | formato: CSV

Ejercicio 3: Vamos a recuperar 100 registros. 
Hacemos una petición con /datastore_search, para que nos dé las filas con los datos. 
Pasamos el recurso concreto que queremos, en este caso "Fitxes_ocupacionals.csv"
con un límite de cien para que me develva cien registros.

In [17]:
resource_id = "d3fffd9f-863c-47a0-bbac-0480b52a5c8b"

In [18]:
data_recu = requests.get(
    url_bcn + "/datastore_search",
    params={"resource_id": resource_id, "limit": 100}
)

print("Estado:", data_recu.status_code)
registros = data_recu.json()["result"]["records"]
print("Registros recuperados:", len(registros))
print("Total disponible en el recurso:", data_recu.json()["result"]["total"])

Estado: 200
Registros recuperados: 100
Total disponible en el recurso: 839

Ejercicio 4. Convertir a Dataframe

In [19]:
df_Ocuapacional = pd.DataFrame(registros)
df_Ocuapacional.head()

,A destacar,Jornada Laboral,Competencies TIC,Altres competències tècniques,Altres denominacions,Retribució,Classificador del contingut per Sector,RRHH i materials,Categoria Professional,Guanys mitjans,...,URL,Descripció autònom,Formació reglada,Valoració del Gestor,Descripcó del contingut (Obligatori),Titol del contingut,Linia,Qualificacions professionals,_id,Formació Complementària
0,,"Jornada completa o parcial, con la realización...",,Manejo básico de un ordenador.Conocimientos de...,Agente de handling de pasajeros; Passenger Ser...,El rango salarial se sitúa entre los 16.061 y ...,Transporte aéreo |,,Personal especializado |,,...,http://w27.bcn.cat/porta22/es/fitxes/A/fitxa44...,,Certificat de Professionalitat de la Família A...,3. Imprescindible,Esta persona es la encargada de atender a los ...,Administrativo/a de handling de pasajeros,1,,1,Es indispensable el conocimiento del inglés co...
1,,Horario por turnos muy variables ya que se deb...,,Conocimientos de informática a nivel de usuari...,Chaquetas rojas,El rango salarial se sitúa entre los 16.061 y ...,Servicios aeroportuarios |,,Personal especializado |,,...,http://w27.bcn.cat/porta22/es/fitxes/A/fitxa44...,,Certificat de Professionalitat de la Família T...,3. Imprescindible,Es la persona que se encarga de atender a los ...,Agente de atenciones especiales,2,,2,"Es necesario tener un buen nivel de inglés, pe..."
2,,Horario por turnos. Depende del horario del ae...,,Nociones de informática a nivel de usuario. Se...,"Agente de apoyo de atención a pasajeros, usuar...",El rango salarial se sitúa entre los 16.965 y ...,Servicios aeroportuarios |,,Personal especializado |,,...,http://w27.bcn.cat/porta22/es/fitxes/A/fitxa44...,,Certificat de Professionalitat de la Família A...,3. Imprescindible,"Este profesional se dedica a atender, ayudar e...",Agente de información al pasajero,3,,3,Conocimiento del inglés superior al nivel del ...
3,,"Los turnos de trabajo son de 8 horas, aunque e...",,Disponer del carnet de conducir B1 o B.Sensibi...,Agente de servicios aeroportuarios; Técnico/a ...,El rango salarial se sitúa entre los 16.061 y ...,Servicios aeroportuarios |,,Cargo intermedio |,,...,http://w27.bcn.cat/porta22/es/fitxes/A/fitxa44...,,,3. Imprescindible,Este/a profesional es responsable de la operat...,Agente responsable de terminal,4,,4,Es imprescindible tener un buen nivel de inglé...
4,,"Jornada completa o parcial, con la realización...",,Imprescindible disponer de carnet de conducir ...,Agente de handling; Baggage handler; Agente de...,El rango salarial se sitúa entre los 15.428 y ...,Transporte aéreo |,,Personal no especializado |,,...,http://w27.bcn.cat/porta22/es/fitxes/O/fitxa44...,,Certificat de Professionalitat de la Família T...,3. Imprescindible,Es la persona encargada de manipular equipajes...,Operador/a de handling de carga,5,,5,La propia empresa realiza un curso de formació...

Ejercicio 5: Guardar el dataframe en un .csv

In [20]:
df_Ocuapacional.to_csv("fitxes_ocupacionals.csv", index=False, encoding="utf-8-sig")